services:
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.volume:/var/lib/localstack"
    networks:
      ls:
        # Set the container IP address in the 192.168.0.0/24 subnet
        ipv4_address: 192.168.0.20
  capxmldb:
    build:
      context: ../docker/cap-xml-db
      dockerfile: Dockerfile
      ssh:
        - default=${SSH_AUTH_SOCK}
    user: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      # IMPORTANT
      # Named volumes ensure portability across the host plaforms used to
      # create and run development containers.
      - capxmlpgdata:/var/lib/postgresql/data
      - capxmlpgbootstrap:/docker-entrypoint-initdb.d
      - capxmlpgtmp:/tmp
    networks:
      ls:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  capxmlpgdata:
    external: true
  capxmlpgbootstrap:
    external: true
  capxmlpgtmp:
    external: true